apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: react-app-sample
  labels:
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: react-app-sample
spec:
  source:
    git:
      url: https://github.com/seagomezar/react-sample-app
      ref:
        branch: main
